# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SupreetOP/Flyrank/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## My Lane as an ML Task (Type)

**Chosen Lane:** Refresh / Content Opportunity Scoring

**ML Task Type:** Scoring (with Ranking)

I chose **Refresh / Content Opportunity Scoring**, which is primarily a **scoring** task. The goal is to assign each webpage a **Refresh Opportunity Score** based on its search performance, engagement, and content characteristics. The pages are then **ranked** from highest to lowest score so content teams can focus on the pages with the greatest potential for improvement. This is not a classification task because pages are not simply labeled as "refresh" or "do not refresh"; instead, each page receives a score that supports prioritization.

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("/content/sample_data/content_refresh_anonymized.csv")

print("ML Task Type : Scoring (Ranking)")
print("Unit of Analysis : One webpage")
print("Dataset Shape :", df.shape)

# Display a few rows
df.head()

ML Task Type : Scoring (Ranking)
Unit of Analysis : One webpage
Dataset Shape : (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## Target or Proxy

**Target:** Refresh Opportunity Score

This project predicts a **Refresh Opportunity Score** for each webpage. Since there is no direct label that says whether a page should be refreshed, the target is a **proxy** rather than an observed outcome.

The proxy score is derived from existing search performance, engagement, and content-related signals such as impressions, CTR, content age, and other available features. Pages with lower performance and higher refresh potential are expected to receive higher scores, helping content teams prioritize their review efforts.

In [2]:


df["refresh_opportunity_score"] = (
    df["content_age_days"] * (1 - df["ctr"])
)

df[["content_age_days", "ctr", "refresh_opportunity_score"]].head()

   content_age_days   ctr  refresh_opportunity_score
0               187  0.76                      44.88
1               445  0.05                     422.75
2               141  0.09                     128.31
3               463  0.49                     236.13
4               263  0.13                     228.81

## Success Metric

**Success Metric:** Precision@10

I chose **Precision@10** as the primary success metric because the goal is to rank webpages that should be reviewed first. Precision@10 measures how many of the top 10 recommended pages are actually valuable refresh opportunities. A higher Precision@10 means the model is helping content teams spend their time on the most important pages.

If ground-truth labels are not available, the quality of the recommendations can also be evaluated through expert review by SEO or content teams.

In [3]:
# Example: Number of pages in the dataset
print("Total webpages:", len(df))

print("\nExample Success Metric")
print("Metric: Precision@10")
print("Goal: Maximize the number of truly high-opportunity pages in the Top 10 recommendations.")

Total webpages: 30000

Example Success Metric
Metric: Precision@10
Goal: Maximize the number of truly high-opportunity pages in the Top 10 recommendations.

## The Unit of Analysis

The unit of analysis is **one webpage**.

Each row in the dataset represents a single webpage and contains search performance, engagement, and content-related features. The ML model will assign a Refresh Opportunity Score to each webpage, allowing the pages to be ranked by their refresh priority.

In [4]:
import pandas as pd

# Load dataset
df = pd.read_csv("/content/sample_data/content_refresh_anonymized.csv")

print("Dataset Shape:", df.shape)

print("\nOne row represents one webpage.\n")

# Display the first 5 webpages
df.head()

Dataset Shape: (30000, 44)

One row represents one webpage.

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [5]:
# Show the available columns
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [6]:
# Display a few important columns (only those that exist)
important_columns = [
    "page_id",
    "impressions_90d",
    "ctr",
    "content_age_days"
]

available = [col for col in important_columns if col in df.columns]

df[available].head()

   impressions_90d   ctr  content_age_days
0             3803  0.76               187
1            15320  0.05               445
2            12581  0.09               141
3            11751  0.49               463
4            19140  0.13               263

## Why ML Beats a Fixed Rule Here

A fixed rule such as "refresh every page older than 365 days" or "refresh pages with CTR below 1%" is too simple because webpage performance depends on multiple factors at the same time. A page may be old but still perform well, while a newer page may have low engagement and high improvement potential.

Machine learning can consider several features together, such as impressions, CTR, content age, engagement, and other search signals, to estimate a Refresh Opportunity Score. This allows the model to identify more meaningful patterns than a single if-statement or threshold, making the recommendations more useful for content teams.

In [7]:
# Example features that could be used together
features = [
    "impressions_90d",
    "ctr",
    "content_age_days"
]

available_features = [f for f in features if f in df.columns]

print("Example features used together by an ML model:")
print(available_features)

Example features used together by an ML model:
['impressions_90d', 'ctr', 'content_age_days']

## Self-check

- [ ] Every section above is filled with both markdown explanations and supporting code where required.
- [ ] The notebook runs from top to bottom without any errors (Runtime → Run all).
- [ ] No client names, URLs, or private search queries are included anywhere in the notebook.
- [ ] My claims use careful language such as **observed**, **measured**, **directional**, and **decision-support**, and I avoid making causal or guaranteed claims.
- [ ] The notebook has been saved as `work/notebooks/w02_ml_task_framing.ipynb`, committed to my repository, and is ready for submission.